Name= input("Enter the name:")
Employeeid=input("Enter the Employeeid")
Department=input("Enter the Department")
Experience= int(input("Enter the Experience"))
Monthly_Salary =int(input("Enter Monthly_Salary"))
print("My Name is",Name)
print("My employee id is", Employeeid)
print("I am from",Department)
print("My experience is",Experience)
print("My salary is", Monthly_Salary)
